# **Taller 4**
**Integrante:**

Anthony Alvarado
27.321.522

In [26]:
#Taller 4

#Anthony Alvarado Javier Rodriguez 27.321.522




#LIBRERIAS.
import numpy as np

#CODIGO.

#Definición de la matriz solicitada, la cual va a tener 6 nodo (A,B,C,D,E,F)
#la misma va a tener un ciclo (A->B; B->C; C->A) y un sumidero (D_ij=0).
#Todas las relaciones que pense (8 en total) para esta matriz son:
# A->B; B->C; C->A; C->D; E->D; F->A; F->E; B->F.
#Generando la siguiente Matriz de adyacencia:
Matriz = np.array([
    #A  B  C  D  E  F
    [0, 0, 1, 0, 0, 1],  #A
    [1, 0, 0, 0, 0, 0],  #B
    [0, 1, 0, 0, 0, 0],  #C
    [0, 0, 1, 0, 1, 0],  #D
    [0, 0, 0, 0, 0, 1],  #E
    [0, 1, 0, 0, 0, 0]   #F
    ], dtype=float)

print("\nInicio del Algoritmo.")
print("Matriz de adyacencia:")
print(Matriz)
#Ya definida la matriz ahora se procede a hacer la parte 2.1 del taller que es
# matriz de transición (en este caso de Matriz).

cant_nodos = Matriz.shape[0] #Cantidad de nodos de Matriz.

Matriz_Trasicion = np.zeros((cant_nodos, cant_nodos)) #Matriz nueva de n*n.

grados_salida = np.sum(Matriz, axis=0) #Grados de salida.

for i in range(cant_nodos):
  if grados_salida[i] > 0:
    #Caso que no es un sumidero.
    Matriz_Trasicion[:, i] = Matriz[:, i] / grados_salida[i]
  else:
    #Caso que si es el sumidero, es decir sus grados de salida = 0
    Matriz_Trasicion[:, i] = 1.0 / cant_nodos

print("\nMatriz de transición:")
print(Matriz_Trasicion)
#Ahora se procede a hacer la parte 2.2 del Taller, con la matriz de transición lista se calcula la matriz de Google.

d = 0.85 #d dado en el enunciado.

J = np.ones((cant_nodos,cant_nodos)) #Matriz de n*n

#Se aplica la formula:

G = d * Matriz_Trasicion + ((1 - d) / cant_nodos) * J

print("\nMatriz de Google:")
print(G)
print("\nVerificacion de la Matriz de Google:")
tempo= np.sum(G, axis=0)
print(tempo)
#Parte 3 del Taller Método de la Potencia.

Tolerancia = 1e-8 #Dado en el enunciado.

max_iteraciones = 1000 #No lo da el enunciado, pero lo coloco para evitar quedarme en un bucle infinito.

v_actual = np.ones(cant_nodos) /cant_nodos #Inicio v^(0) asi para que todos tengan 1/6, es decir, sean iguales.

inter = 0 #Paso actual.

Error = float('inf')

while inter < max_iteraciones and Error > Tolerancia: #Se hace mientras las interaciones sean menor a 1000 y el error menor a 1e-8.
  #Calcular el nuevo vector: v^(k+1) = G * v^(k).

  v_nuevo = np.dot(G, v_actual)

  #Calcular el error.

  Error = np.linalg.norm(v_nuevo - v_actual, ord=1)

  #Actualizar.

  v_actual = v_nuevo
  inter += 1
print("\n¡Fin del algoritmo!")
print(f"Número total de iteraciones: {inter}")

# --- PRESENTACIÓN DE RESULTADOS ---
print("\n--- RANKING FINAL DE PÁGINAS ---")
nombres_nodos = [chr(65 + i) for i in range(cant_nodos)]

for i in range(cant_nodos):
    print(f"Página {nombres_nodos[i]}: PageRank = {v_actual[i]:.6f}")

# Ordenar de mayor a menor importancia
ranking_ordenado = sorted(zip(nombres_nodos, v_actual), key=lambda x: x[1], reverse=True)
print("\nOrden de relevancia de mayor a menor:")
for lugar, (nodo, score) in enumerate(ranking_ordenado, start=1):
    print(f"{lugar}°. Nodo {nodo} ({score:.6f})")







Inicio del Algoritmo.
Matriz de adyacencia:
[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]]

Matriz de transición:
[[0.         0.         0.5        0.16666667 0.         0.5       ]
 [1.         0.         0.         0.16666667 0.         0.        ]
 [0.         0.5        0.         0.16666667 0.         0.        ]
 [0.         0.         0.5        0.16666667 1.         0.        ]
 [0.         0.         0.         0.16666667 0.         0.5       ]
 [0.         0.5        0.         0.16666667 0.         0.        ]]

Matriz de Google:
[[0.025      0.025      0.45       0.16666667 0.025      0.45      ]
 [0.875      0.025      0.025      0.16666667 0.025      0.025     ]
 [0.025      0.45       0.025      0.16666667 0.025      0.025     ]
 [0.025      0.025      0.45       0.16666667 0.875      0.025     ]
 [0.025      0.025      0.025      0.16666667 0.025      0.45      ]
 [0.025      0.45       0.